sudo: required

services:
  - docker

before_script:
  - docker login -u "$DOCKER_USER" -p "$DOCKER_PASS"

script:
  - cd prometheus && docker build -t stefanprodan/swarmprom-prometheus:$TRAVIS_BUILD_NUMBER .
  - cd .. && cd node-exporter && docker build -t stefanprodan/swarmprom-node-exporter:$TRAVIS_BUILD_NUMBER .
  - cd .. && cd alertmanager && docker build -t stefanprodan/swarmprom-alertmanager:$TRAVIS_BUILD_NUMBER .
  - cd .. && cd dockerd-exporter && docker build -t stefanprodan/swarmprom-dockerd-exporter:$TRAVIS_BUILD_NUMBER .
  - docker tag stefanprodan/swarmprom-prometheus:$TRAVIS_BUILD_NUMBER stefanprodan/swarmprom-prometheus:latest
  - docker push stefanprodan/swarmprom-prometheus:latest
  - docker tag stefanprodan/swarmprom-node-exporter:$TRAVIS_BUILD_NUMBER stefanprodan/swarmprom-node-exporter:latest
  - docker push stefanprodan/swarmprom-node-exporter:latest
  - docker tag stefanprodan/swarmprom-alertmanager:$TRAVIS_BUILD_NUMBER stefanprodan/swarmprom-alertmanager:latest
  - docker push stefanprodan/swarmprom-alertmanager:latest
  - docker tag stefanprodan/swarmprom-dockerd-exporter:$TRAVIS_BUILD_NUMBER stefanprodan/swarmprom-dockerd-exporter:latest
  - docker push stefanprodan/swarmprom-dockerd-exporter:latest
